### ISSUE TITLE
TLS config is resulting in an error

### ISSUE THREAD

**Issue by HansBambel** [davidmirror-ops/flyte-the-hard-way#29]
Thank you for the tutorial!

I noticed that when I tried to add ingress that updating the helm-chart resulted in an error.

The [tutorial](https://github.com/davidmirror-ops/flyte-the-hard-way/blob/main/docs/on-premises/single-node/003-ingress-tls.md#configuring-ssl) says to add the following:
```yaml
ingress:
  tls:
    enabled: true
    - hosts:
      - "flyteonprem.fthw.local"#replace with your hostname
     secretName: flytetls
  ...
```

This results in the following error: `Error: failed to parse onprem-flyte-binary-values.yaml: error converting YAML to JSON: yaml: line 51: did not find expected key`

After some debugging I found this configuration to be working:

```yaml
ingress:
 enabled: true
 tls:
   - hosts:
       - "flyteonprem.fthw.local"
     secretName: flytetls
```

The issue is that we're trying to mix a mapping (enabled: true) and a sequence (- hosts:) at the same indentation, so the parser doesn’t know whether tls: is supposed to be a map or a list.
